BUILDROOT=${PWD}

GLI_VERSION = 4.5.30
OPENBLAS_VERSION=0.3.5
PYTHON_VERSION=3.6.8
NUMPY_VERSION=1.16.1
SCIPY_VERSION=1.2.1
MDSPLUS_VERSION=stable_release-7-7-8
BLITZ_VERISON=1.0.0 # Apparently the same as 0.10.0
LIBXML2_VERSION=2.9.1
SAXON_VERSION=HE9-8-0-12J
IMASDD_VERSION=3.21.0
IMASUAL_VERSION=3.8.4
GGD_VERSION=1.8.3
SOLPS_VERSION=3.0.7

.PHONY: imas gr gli OpenBLAS mscl ggd solps-iter

all: imas gr gli OpenBLAS mscl ggd

imas: OpenBLAS
	BUILDROOT=${BUILDROOT} \
	PYTHON_VERSION=${PYTHON_VERSION} \
	NUMPY_VERSION=${NUMPY_VERSION} \
	SCIPY_VERSION=${SCIPY_VERSION} \
	MDSPLUS_VERSION=${MDSPLUS_VERSION} \
	BLITZ_VERSION=${BLITZ_VERSION} \
	LIBXML2_VERSION=${LIBXML2_VERSION} \
	SAXON_VERSION=${SAXON_VERSION} \
	IMASDD_VERSION=${IMASDD_VERSION} \
	IMASUAL_VERSION=${IMASUAL_VERSION} \
	./build-imas.sh
gr:
	BUILDROOT=${BUILDROOT} ./build-GR.sh
gli:
	BUILDROOT=${BUILDROOT} GLI_VERSION=${GLI_VERSION} ./build-GLI.sh
OpenBLAS:
	BUILDROOT=${BUILDROOT} OPENBLAS_VERSION=${OPENBLAS_VERSION} ./build-OpenBLAS.sh
mscl:
	./build-mscl.sh
ggd: imas
	BUILDROOT=${BUILDROOT} \
	GGD_VERSION=${GGD_VERSION} \
	IMASUAL_VERSION=${IMASUAL_VERSION} \
	IMASDD_VERSION=${IMASDD_VERSION} \
	MDSPLUS_VERSION=${MDSPLUS_VERSION} \
	./build-ggd.sh
solps-iter: # imas gr gli OpenBLAS mscl ggd
	# Copy imasdb script for setting up IMAS MDSPLUS_TREE environment
	cp ${BUILDROOT}/imasdb ${STAGING_DIR}/bin
	./build-solps-iter.csh
query-%:
	@echo $($(*))
deep-clean:
	rm -rf ${DOWNLOAD_DIR} ${BUILD_DIR} ${STAGING_DIR}
