# source this bash file for local environment if PyQT is provided locally
export QTDIR="${PWD}/staging/qt/5.7.0"
export PATH="${PWD}/staging/bin:${QTDIR}/bin:${PATH}"
export LD_LIBRARY_PATH="${PWD}/staging/lib:${QTDIR}/lib:${LD_LIBRARY_PATH}"
export PKG_CONFIG_PATH="${PWD}/staging/lib/pkgconfig:${PKG_CONFIG_PATH}"
export PYTHONPATH="${PWD}/src/widgets:${PYTHONPATH}"
export PYQTDESIGNERPATH="${PWD}/src/plugins/designer:${PYQTDESIGNERPATH}"
alias solps="${PWD}/staging/bin/python3 ${PWD}/src/gui/solps.py"
alias solps_doc="xdg-open ${PWD}/doc/build/html/index.html"
alias solps_help="assistant -collectionFile ${PWD}/doc/build/qthelp/SOLPSGUI.qhc"
