# source this bash file for local environment if PyQT is provided locally
export QT_QPA_FONTDIR=/usr/share/fonts/dejavu
export QTDIR="${PWD}/staging/qt/5.9.1"
export PARAVIEW_PREFIX="${PWD}/staging/paraview/5.4.1"
export PATH="${PWD}/staging/bin:${QTDIR}/bin:${PARAVIEW_PREFIX}/bin:${PATH}"
export LD_LIBRARY_PATH="${PWD}/staging/lib:${QTDIR}/lib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH=${PWD}/staging/access-layer/3.8.4/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${PWD}/staging/mdsplus/stable_release-7-7-8/lib:${LD_LIBRARY_PATH}
export ids_path=${PWD}/staging/access-layer/3.8.4/models/mdsplus
export PKG_CONFIG_PATH="${PWD}/staging/lib/pkgconfig:${QTDIR}/lib/pkgconfig:${PKG_CONFIG_PATH}"
export PYTHONPATH="${PWD}/src/widgets:${PYTHONPATH}"
export PYTHONPATH="/local/work/simicg/solps-gui/staging/access-layer/3.8.4/python/lib.linux-x86_64-3.6:${PYTHONPATH}"
export PYQTDESIGNERPATH="${PWD}/src/plugins/designer:${PYQTDESIGNERPATH}"
export SOLPSGUI="${PWD}/src/gui"
alias solps="${PWD}/staging/bin/python3 ${PWD}/src/gui/solps.py"
alias solps_doc="xdg-open ${PWD}/doc/build/html/index.html"
alias solps_help="assistant -collectionFile ${PWD}/doc/build/qthelp/SOLPSGUI.qhc"
alias eirene="python3 ${PWD}/src/widgets/eirene.py"
alias b2="python3 ${PWD}/src/widgets/b2.py"
