#!/usr/bin/env python3
""" A PyQt widget for Triang process.
"""

from PySide6.QtWidgets import (QPlainTextEdit, QVBoxLayout, QGridLayout,
                             QInputDialog, QSpacerItem, QSizePolicy,
                             QPushButton, QGroupBox, QCheckBox, QMessageBox)
from PySide6.QtCore import Slot, QSettings, Qt, QDateTime
from PySide6.QtGui import QTextCursor
from tcsh_process import TcshProcess
import logging
import os
import sys
import glob

TIME = QDateTime()
TIME_FORMAT = "ddd MMM d t yyyy"


class TriangVars:
    """Class that contains the names of the steps and their respected command
    for the triang script. The main concern was for the automation of creating
    the GUI for :class:`Triang`.

    Attributes:
        NumOfVars (int): Integer of how many steps are in triang script
        Name (dict): Contains the string representation for the enumeration of
            steps
        command (dict): Contains the the string commands for the enumeration of
            steps
        Values (dict): Contains the integer values for the string names for the
            steps
        Default (dict): Contains the default (0) value for all steps.
        Uinp (int): The **Uinp(U)** step for ``triang`` script
        uinp (int): The **uino(u)** step for ``triang`` script
        B2ag (int): The **b2ag(b)** step for ``triang`` script
        Eirene (int): The **Eirene(e)** step for ``triang`` script
        Tria (int): The **Tria(t)** step for ``triang`` script
        triaGeom (int): The **triaGeom(g)** step for ``triang`` script
        Store (int): The **Store(s)** step for ``triang`` script
        Conv2Out (int): The **Convert(c)** step for ``triang`` script, to
            convert the triangular mesh to a DivGeo template
        Conv2Grid (int): The **Convert(C)** step for ``triang`` script, to
            convert the combined mesh to a DivGeo template
    """
    NumOfVars = 9

    Uinp, uinp, b2ag, eirene, tria, triaGeom, store, outTemp, gridTemp = \
        range(NumOfVars)

    Name = {0: 'Uinp(U)', 1: 'Uinp(u)', 2: 'B2ag', 3: 'Eirene', 4: 'Tria',
            5: 'triaGeom', 6: 'Store', 7: 'Conv2Out (c)', 8: 'Conv2Grid (C)'}

    command = {0: 'U', 1: 'u', 2: 'b', 3: 'e', 4: 't', 5: 'g', 6: 's', 7: 'c',
               8: 'C'}

    Values = {'Uinp(U)': 0, 'Uinp(u)': 1, 'B2ag': 2, 'Eirene': 3, 'Tria': 4,
              'triaGeom': 5, 'Store': 6, 'Conv2Out (c)': 7, 'Conv2Grid (C)': 8}

    Default = {i: 0 for i in range(NumOfVars)}


class TriangState:
    """The state of the QProcess when running the triang script.

    AttributeS:
        notRunning (int): Means that the TCSH QProcess is not running.
        starting (int): Means that the TCSH QProcess is starting and sourcing
            setup.csh from ``SOLPSTOP``.
        waiting (int): Means that the triang script is running and waiting for
            the users input
        stepRunning (int): Means that one of the step is still running.
    """
    notRunning, starting, waiting, stepRunning = range(4)


class Triang(TcshProcess):
    """Widget for running triang in a baserun directory.

    It runs the triang script from ``SOLPSTOP/scripts`` directory in the
    selected baserun directory. It does not run in directories which names
    are not baserun.

    It has self-assessment control for the user to record what parts were run
    and which were not.

    For the step ``b2ag`` a handy button called :guilabel:`Edit b2ag.dat` is
    there for the user in case the mesh generated by Carre has been modified by
    hand.

    The widget contains:

     - QCheckBox-es for self-assessment
     - QProcess for running a TCSH shell
     - QPlainTextEdit for displaying the output of Triang
     - QPushButtons for interacting with the triang script

    In the :func:`__init__` the interface and variables are prepared, and
    certain functions are connected to the output signals from :attr:`tcsh` to
    process the output.

    Attributes:
        vars (dict): A dictionary for the status of steps in the current
            :attr:`runDir`
        currentRunDir (str): A string in which the current Triang is
            running.
        STATE (int): The status variable for :attr:`tcsh`
    """

    def __init__(self, parent=None):
        super(Triang, self).__init__(parent)
        # self.activateDebugging()
        # Creating QPlainTextEdit
        self.vars = TriangVars.Default
        self.prepareUserInterface()

        self.tcsh.readyReadStandardOutput.connect(self.tcsh.readStdOut)
        settings = QSettings('ITER', 'solps-gui')
        self.tcsh.setTcshPath(settings.value('tcsh_path', '/usr/bin/tcsh'))
        self.tcsh.prcStateChanged.connect(self.updateText)
        self.tcsh.prcFinished.connect(self.updateText)
        self.tcsh.prcError.connect(self.updateError)
        self.tcsh.stdOutput.connect(self.updateText)
        self.tcsh.stdErrOutput.connect(self.updateError)

        self.currentRunDir = ''
        self.STATE = TriangState.notRunning

    def prepareUserInterface(self):
        """ Prepares the interface. It is made by hand, since this way, I have
        better control over the placing, setting the attributes etc.

        The main layout is a *QVBoxLayout* and is halved into an upper and
        lower QGridLayout.

        The upper QGridLayout contains the QCheckBoxes for self-assessment.
        The lower QGridLayout contains the interface for the triang script and
        an output window.
        """
        mainLayout = QVBoxLayout()
        mainLayout.setSpacing(0)
        mainLayout.setContentsMargins(0, 0, 0, 0)

        upperGridLayout = QGridLayout()
        lowerGridLayout = QGridLayout()

        #############
        # Group Box 1
        groupBox1 = QGroupBox()
        self.clickedGroup = groupBox1
        groupLayout = QGridLayout()
        groupBox1.setTitle('Baserun .status')
        _n = 2  # Number of widgets per column
        for i in range(TriangVars.NumOfVars // _n):
            for j in range(_n):
                # Creating checkboxes for
                x = QCheckBox(TriangVars.Name[i * _n + j])
                x.setCheckState(Qt.Unchecked)
                x.stateChanged.connect(self.setVarsFromClickedGroup)
                groupLayout.addWidget(x, j, i)
        leftOver = TriangVars.NumOfVars - (TriangVars.NumOfVars // _n) * _n
        if leftOver > 0:
            for k in range(leftOver):
                x = QCheckBox(TriangVars.Name[(i + 1) * _n + k])
                x.setCheckState(Qt.Unchecked)
                x.stateChanged.connect(self.setVarsFromClickedGroup)
                groupLayout.addWidget(x, k, i + 1)
        groupBox1.setLayout(groupLayout)
        # Group Box 1
        #############

        upperGridLayout.addWidget(groupBox1, 0, 0)

        upperGridLayout.addItem(QSpacerItem(20, 40,
                                            hData=QSizePolicy.Expanding),
                                0, 2)

        #############
        # Group Box 2
        groupBox2 = QGroupBox()
        groupBox2.setTitle('Steps')
        groupLayout = QVBoxLayout()
        groupLayout.setSpacing(0)
        groupLayout.setContentsMargins(0, 0, 0, 0)

        start = QPushButton('Start Triang')
        start.clicked.connect(self.startTriang)
        groupLayout.addWidget(start)

        # Manually set the QPushButton
        p = QPushButton("Uinp(U)")
        p.clicked.connect(self.runUinpU)
        groupLayout.addWidget(p)
        p = QPushButton("Uinp(u)")
        p.clicked.connect(self.runUinpu)
        groupLayout.addWidget(p)
        p = QPushButton("B2ag")
        p.clicked.connect(self.runB2ag)
        groupLayout.addWidget(p)
        p = QPushButton("Eirene")
        p.clicked.connect(self.runEirene)
        groupLayout.addWidget(p)
        p = QPushButton("Tria")
        p.clicked.connect(self.runTria)
        groupLayout.addWidget(p)
        p = QPushButton("triaGeom")
        p.clicked.connect(self.runtriaGeom)
        groupLayout.addWidget(p)
        p = QPushButton("Store")
        p.clicked.connect(self.runStore)
        groupLayout.addWidget(p)
        p = QPushButton("Conv2Out (c)")
        p.clicked.connect(self.runConv2Out)
        groupLayout.addWidget(p)
        p = QPushButton("Conv2Grid (C)")
        p.clicked.connect(self.runConv2Grid)
        groupLayout.addWidget(p)

        groupLayout.addItem(QSpacerItem(40, 20, vData=QSizePolicy.Expanding))
        groupBox2.setLayout(groupLayout)
        # Group Box 2
        #############

        lowerGridLayout.addWidget(groupBox2, 0, 0)

        #############
        # Group Box 3
        groupBox3 = QGroupBox()
        groupBox3.setTitle('Log window')

        self.textDisplay = QPlainTextEdit()
        self.textDisplay.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.textDisplay.setReadOnly(True)

        groupLayout = QGridLayout()
        groupLayout.setContentsMargins(0, 0, 0, 0)
        groupLayout.setSpacing(0)
        groupLayout.addWidget(self.textDisplay, 0, 0, 1, -1)

        groupLayout.addItem(QSpacerItem(40, 20, hData=QSizePolicy.Expanding),
                            1, 0)
        editB2ag = QPushButton('Edit b2ag.dat')
        editB2ag.clicked.connect(self.editB2ag)

        groupLayout.addWidget(editB2ag, 1, 1)

        manualInput = QPushButton('Terminal input')
        manualInput.clicked.connect(self.manualInput)

        groupLayout.addWidget(manualInput, 1, 2)

        yes = QPushButton('Yes')
        yes.clicked.connect(self.pressY)

        no = QPushButton('No')
        no.clicked.connect(self.pressN)

        groupLayout.addWidget(yes, 1, 3)
        groupLayout.addWidget(no, 1, 4)
        groupBox3.setLayout(groupLayout)
        # Group Box 3
        #############

        lowerGridLayout.addWidget(groupBox3, 0, 1)

        mainLayout.addLayout(upperGridLayout)
        mainLayout.addLayout(lowerGridLayout)
        self.setLayout(mainLayout)

    def setClickedGroupFromVars(self):
        """ Set the values of QCheckBoxes according to the values stored in
        :attr:`vars`.
        """
        layout = self.clickedGroup.layout()
        for i in range(layout.count()):
            item = layout.itemAt(i).widget()

            item.stateChanged.disconnect()

            if self.vars[i]:
                item.setCheckState(Qt.Checked)
            else:
                item.setCheckState(Qt.Unchecked)

            item.stateChanged.connect(self.setVarsFromClickedGroup)

    @Slot()
    def setVarsFromClickedGroup(self):
        """Set the :attr:`vars` to the checked status of the *QCheckBoxes*.
        """
        layout = self.clickedGroup.layout()
        for i in range(layout.count()):
            item = layout.itemAt(i).widget()
            if item.isChecked():
                self.vars[i] = 1
            else:
                self.vars[i] = 0

    def resetCheckBox(self):
        """Resets the *QCheckBoxes* to the status *unchecked*.
        """
        layout = self.clickedGroup.layout()
        for i in range(layout.count()):
            layout.itemAt(i).widget().setCheckState(Qt.Unchecked)

    def readStatusFile(self, baserunDir):
        """Read the .status file in baserun.

        Variables:
            statusFile (list): text of status without the Triang block.
            mark (int): Where Triang block is inserted into .status file.
        """
        self.resetCheckBox()
        if not baserunDir:
            return

        if not baserunDir.endswith('baserun'):
            return

        file = baserunDir + '/.status'

        # Checking file permission and existance
        ok = os.access(file, os.F_OK | os.R_OK)
        if not ok:
            logging.info("No .status found in baserun " + baserunDir +
                         ", or no permission to read .status.")
            return

        reading = 0
        TriangBlocks = 0
        with open(file, 'r') as f:
            for i, line in enumerate(f):
                if reading and line.startswith('&'):
                    reading = 0

                if reading:
                    try:
                        sline = line.split()
                        if len(sline) == 3:
                            name = sline[0] + ' ' + sline[1]
                            val = sline[2]
                        else:
                            name, val = sline[0], sline[1]
                        self.vars[TriangVars.Values[name]] = int(val) if \
                            val.isdigit else val
                    except KeyError as e:
                        logging.error('Uknown key ' + name)
                    except ValueError as e:
                        logging.error("Wrong value for: " + name)
                    except IndexError as e:
                        logging.error("Not enough arguments on line: " + line)

                if line.startswith('&Triang'):
                    reading = 1  # We are reading the block
                    TriangBlocks += 1
                    if TriangBlocks > 1:
                        logging.error("Multiple Triang block in .status file "
                                      "in baserun: " + baserunDir)
                        break
        self.setClickedGroupFromVars()

    def storeStatusFile(self, baserunDir):
        """Stores the values of attribute :attr:`vars` to the ``.status``
        file in the baserun directory. If there is no such file, it
        is created. If there is a file but no Triang block in the file, it will
        be created at the beginning of the file, i.e.:

        | &Triang
        | par value
        | par value
        | ...
        | par value
        | &

        If the file exists but has no ``READ/WRITE`` access, then the error is
        reported and no status file is stored in the baserun directory.

        Args:
            baserunDir (str): Path to the baserun directory.

        """
        variables = self.vars
        if not baserunDir:
            return
        if not baserunDir.endswith('baserun'):
            return
        logging.info('Storing .status in baserun ' + baserunDir)
        file = baserunDir + '/.status'
        triangLines = [TriangVars.Name[i] + ' ' + str(variables[i]) for i
                      in range(len(variables))]
        if os.access(file, os.F_OK):
            if os.access(file, os.W_OK):
                logging.info(".status file exists in baserun " + baserunDir)
                with open(file, 'r') as f:
                    text = f.read()

                if "&Triang" in text:
                    logging.info("Triang block found in .status file!")
                    left, right = text.split("&Triang", 1)
                    center, right = right.split("&", 1)

                    text = left + "&Triang\n" +'\n'.join(triangLines) + \
                           "\n&" + right

                else:
                    logging.info("No Triang block found in .status file!")
                    text = '&Triang\n' + '\n'.join(triangLines) + '\n&\n' + text

                with open(file, 'w') as f:
                    f.write(text)
                logging.info("Triang Written to .status file.")

            else:
                logging.error("No writing permission to .status file!")

        else:
            logging.info("No .status file exists in baserun " + baserunDir)
            with open(file, 'w') as f:
                text = '&Triang\n'
                text += '\n'.join(triangLines)
                text += '\n&'
                f.write(text)
            logging.info(".status file created for triang block!")

    def appendToStatus(self, msg):
        """Writes the current step, that is running, with a timestamp to the
        .status file in the baserun directory.

        Args:
            msg (str): Message to write to the .status file
        """

        baserunDir = self.runDir
        if not baserunDir:
            return
        path = baserunDir + '/.status'
        if os.access(path, os.W_OK | os.F_OK):
            with open(path, 'a') as f:
                time = TIME.currentDateTime().toString(TIME_FORMAT)
                f.write('\nRan Triang step ' + msg + ' at ' + time)

    @Slot()
    def manualInput(self):
        """Opens a dialog window into which the user can write text, which is
        then provided to the TCSH terminal.
        """
        if not self.tcsh.state():
            return

        msg, ok = QInputDialog.getMultiLineText(self, 'Input dialog',
                                                'Command:')
        if ok:
            self.tcsh.write(msg + '\n')
            self.insertTextAtBottom(msg)

    @Slot()
    def editB2ag(self):
        """Read b2ag.dat if it exists and prompts the user with a
        QInputDialog.getMultiLineText to edit the file and then writes back
        to the file.
        """
        file = self.getRunDir() + '/b2ag.dat'

        # Get .sno file
        env = QSettings('ITER', 'solps-gui')
        device = env.value('device_environment', 'iter')

        solpstop = self.tcsh.findSolpsTop(self.getRunDir())
        if solpstop:
            # Directory to Divgeo/device/$device

            deviceDir = solpstop + '/modules/DivGeo/device/' + device

            snoFile = self.findLatestFile(deviceDir, '*.sno')

        else:
            deviceDir = ''
            snoFile = ''

        snoFile = os.path.basename(snoFile)

        if os.access(file, os.F_OK | os.W_OK | os.R_OK):
            with open(file, 'r') as f:
                text = f.read()
            text += '\n! Latest SNO file in ' + 'DivGeo/device/' + device + \
                    ': ' + snoFile
            text += '\n! Change the b2agfs_geometry value with: ' + snoFile
            text += '\n! Change The first value of *param from -1 to -2'
            msg, ok = QInputDialog.getMultiLineText(self, 'Input dialog',
                                                    'Edit b2ag.dat',
                                                    text)
            if ok:
                with open(file, 'w') as f:
                    f.write(msg)
        else:
            QMessageBox.information(self, 'Information', 'File b2ag.dat in ' +
                                    self.getRunDir() + ' either does not exist'
                                    ' or you do not have permission to wrie/'
                                    'read!')

    @Slot()
    def runStep(self):
        """Custom PushButtons emits signal to this function. They contain
        attribute value which is then passed to tcsh if it is running.
        """
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            sender = self.sender()
            self.appendToStatus(sender.text())
            msg = sender.value + '\n'
            self.tcsh.write(msg)
    @Slot()
    def runUinpU(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "U\n"
            self.tcsh.write(msg)
    @Slot()
    def runUinpu(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "u\n"
            self.tcsh.write(msg)
    @Slot()
    def runB2ag(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "b\n"
            self.tcsh.write(msg)
    @Slot()
    def runEirene(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "e\n"
            self.tcsh.write(msg)
    @Slot()
    def runTria(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "t\n"
            self.tcsh.write(msg)
    @Slot()
    def runtriaGeom(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "g\n"
            self.tcsh.write(msg)
    @Slot()
    def runStore(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "s\n"
            self.tcsh.write(msg)
    @Slot()
    def runConv2Out(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "c\n"
            self.tcsh.write(msg)
    @Slot()
    def runConv2Grid(self):
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "C\n"
            self.tcsh.write(msg)

    @Slot()
    def pressY(self):
        """Command Store or value 't'
        """
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "y\n"
            self.tcsh.write(msg)

    @Slot()
    def pressN(self):
        """Command Store or value 't'
        """
        if not self.tcsh.state():
            return
        if self.STATE == TriangState.waiting:
            msg = "n\n"
            self.tcsh.write(msg)

    def processText(self, text):
        """This function waits for the correct output of the triang script so
        we know when we can start running the steps.

        Args:
            text (str): The output text of the triang script from
            ``SOLPSTOP/scripts``
        """
        default = "Help, Uinp, B2ag, Eirene, Tria, triaGeom, Plot, View, " \
                  "Store, Convert, List, Remove, reMap, Inquire, Quit ?"
        if default in text:
            self.STATE = TriangState.waiting

    def insertTextAtBottom(self, msg):
        """Inserts the string *msg* at the bottom of the QPlainTextEdit
        *textDisplay* without inserting a new line.

        Args:
            msg (str): Text to be inserted to the bottom of *textDisplay*
        """
        self.textDisplay.moveCursor(QTextCursor.End)
        if msg.endswith('\n'):
            msg = msg[:-1]
        self.textDisplay.insertPlainText('\n' + msg)
        self.textDisplay.moveCursor(QTextCursor.End)

    # Overloaded
    @Slot(str)
    def setRunDir(self, runDir):
        """Overloaded function of :meth:`tcsh_process.Tcsh.setRunDir`.
        Additionally to setting the new directory, it is also tested whether
        the directory is a **baserun** directory.

        If we select a new baserun directory from the ``Runs`` tab of
        ``SOLPS-GUI`` the following happens:

        1. If we left a baserun directory, then update the .status file.
        2. Stop current TCSH terminal.
        3. Read the new .status file in the new baserun directory.
        4. Start the TCSH terminal in the new baserun directory.

        Arguments:
            runDir (str): New run directory.
        """
        if runDir != self.runDir:
            self.storeStatusFile(self.runDir)
        if runDir.endswith('baserun'):
            self.readStatusFile(runDir)
            self.stopTriang()
        super(Triang, self).setRunDir(runDir)

    @Slot(str)
    def updateText(self, text):
        """Read the output given from Triang, and when input is expected, spawn
        input dialogs to get input from the user and then pass it back to
        Triang.
        """
        # self.insertTextAtBottom(text)
        self.processText(text)  # Triang script outputs via StdError...
        if self.STATE >= TriangState.waiting:
            self.insertTextAtBottom(text)

    @Slot(str)
    def updateError(self, text):
        # color_pref = '<font color=red>'
        # color_post = '</font>'
        # self.textDisplay.appendHtml('<b>' + color_pref + text + color_post +
        #                             '</b>')
        if "does not exist. Create it?" in text:
            self.tcsh.write('y\n')
        if self.STATE >= TriangState.starting:
            self.processText(text)
        if self.STATE >= TriangState.waiting:
            self.insertTextAtBottom(text)

    @Slot()
    def startTriang(self):
        """ Starts the ``triang`` script in the baserun directory and with the
        selected device from the *Preferences* settings.
        """

        self.textDisplay.clear()
        if not self.getRunDir():
            self.textDisplay.appendPlainText('No baserun selected.')
            return

        runDir = self.getRunDir()
        if self.getRunDir() != self.currentRunDir:
            msg = 'Baserun changed'
            if self.STATE != TriangState.notRunning:
                msg += '. But current triang run hasn\'t finished yet!'
                logging.warning(msg)
                self.insertTextAtBottom(msg)
                return

            msg += '. Running triang in directory ' + self.currentRunDir + '.'
            logging.info(msg)
            self.currentRunDir = runDir

        if not self.tcsh.state():
            # Get DG model from combo box

            self.startTcsh()
            self.tcsh.waitForStarted()

            cmd = 'cd ' + runDir + '\n'
            self.textDisplay.appendPlainText('Sourcing setup.csh. It will '
                                             'take a while.')
            self.tcsh.write(cmd)
        else:
            logging.info('TCSH for triang is aready running.')

        self.STATE = TriangState.starting
        Triang = 'triang\n'
        cmd = Triang + '\n'
        # self.tcsh.write(cmd)
        self.tcsh.write(cmd)

    def stopTriang(self):
        if self.tcsh.state():
            self.textDisplay.clear()
            self.tcsh.terminate()
            self.tcsh.close()
            self.STATE = TriangState.notRunning
            msg = "Switched to another baserun, therefore stopped carre."
            self.textDisplay.appendPlainText(msg)

    def findLatestFile(self, directory, suffix):
        """Find the latest file in the directory *directory* and with the
        suffix *suffix* (i.e., '\*.dg').

        Args:
            directory (str): Path to directory
            suffix (str): The suffix of file.
        Returns:
            string: The newest file in the directory with the provided suffix.
        """
        files = glob.glob(directory + '/' + suffix)
        if files:
            return max(files, key=os.path.getctime)
        else:
            return ''


if __name__ == '__main__':
    from PySide6.QtWidgets import (QApplication, QMainWindow, QWidget)
    env = QSettings('ITER', 'solps-gui')
    env.setValue('device_environment', 'cmod')
    app = QApplication(sys.argv)
    main = QMainWindow()
    triangM = Triang()
    triangM.activateDebugging()
    triangM.setTcshPath('/bin/tcsh')
    path = os.path.expanduser('~/solps-iter/runs/test_run/baserun')
    triangM.setRunDir(path)

    layout = QVBoxLayout()
    layout.setContentsMargins(0, 0, 0, 0)
    layout.addWidget(triangM)

    window = QWidget()
    window.setLayout(layout)

    main.setCentralWidget(window)
    main.show()

    res = app.exec()
    app.quit()
    sys.exit(res)
